//! Noctalia's own path and launcher knowledge: the v4 Quickshell paths and
//! the v5 native paths, plus the `ShellProvider` trait those paths implement.
//!
//! This file used to be called `shell.rs` and read as if it were the generic
//! shell seam. It never was: every impl here is Noctalia. The generic seam now
//! lives in `shell_capabilities.rs`; naming this module after its owner is the
//! honest fix.

use std::path::{Path, PathBuf};

/// A shell knows how to resolve its configuration paths and perform shell-specific
/// operations like wallpaper IPC.
///
/// Includes source/rendered file lists, template processor paths, and
/// wallpaper IPC operations.
pub trait ShellProvider: Send + Sync {
    // The four methods below are exercised only by the test suite (and by
    // `ShellRegistry`, itself tests-only); production code (noctalia.rs) uses
    // the remaining methods. The allows are required: rustc's dead_code lint
    // does not count `#[cfg(test)]` usage during a plain `cargo check`.
    #[allow(dead_code)]
    fn id(&self) -> &str;
    #[allow(dead_code)]
    fn display_name(&self) -> &str;
    fn config_dir(&self) -> Option<PathBuf>;
    fn rendered_dir(&self) -> Option<PathBuf>;
    fn wallpapers_file(&self) -> Option<PathBuf>;
    fn theming_config(&self) -> Option<PathBuf>;
    fn source_files(&self) -> Vec<&'static str>;
    fn rendered_color_files(&self) -> Vec<&'static str>;
    fn template_processor(&self) -> Option<PathBuf>;
    #[allow(dead_code)]
    fn reload_command(&self) -> Vec<String>;
    fn apply_wallpaper(&self, _path: &Path, _screen: &str) -> Result<(), String> {
        Ok(())
    }
    #[allow(dead_code)]
    fn get_wallpaper(&self, _screen: &str) -> Result<String, String> {
        Err("not supported".into())
    }
}

/// Source config files we snapshot for Noctalia.
const NOCTALIA_FILES: &[&str] = &["settings.json", "colors.json", "plugins.json"];

/// Rendered color files generated by Noctalia in the Hyprland config dir.
/// These are what `colors.sh` actually reads, and what Hyprland sources.
const NOCTALIA_RENDERED_FILES: &[&str] = &["noctalia-colors.conf", "noctalia-colors.lua"];

/// Default paths for Noctalia v4.
///
/// Supports three levels of customization (descending priority):
/// 1. Environment variables: `HVE_NOCTALIA_CONFIG`, `HVE_NOCTALIA_HYPR`,
///    `HVE_NOCTALIA_TEMPLATE_PROCESSOR`
/// 2. System paths: `/etc/xdg/quickshell/noctalia-shell/...`
/// 3. Standard locations: `dirs::config_dir()`, `~/.config/...`
pub struct NoctaliaV4Paths;

impl ShellProvider for NoctaliaV4Paths {
    fn id(&self) -> &str {
        "noctalia"
    }

    fn display_name(&self) -> &str {
        "Noctalia v4"
    }

    fn config_dir(&self) -> Option<PathBuf> {
        if let Ok(dir) = std::env::var("HVE_NOCTALIA_CONFIG") {
            let p = PathBuf::from(dir);
            if p.exists() {
                return Some(p);
            }
        }
        dirs::config_dir().map(|d| d.join("noctalia"))
    }

    fn rendered_dir(&self) -> Option<PathBuf> {
        if let Ok(dir) = std::env::var("HVE_NOCTALIA_HYPR") {
            let p = PathBuf::from(dir);
            if p.exists() {
                return Some(p);
            }
        }
        dirs::home_dir().map(|d| d.join(".config").join("hypr").join("noctalia"))
    }

    fn wallpapers_file(&self) -> Option<PathBuf> {
        let home = std::env::var("HOME").ok()?;
        Some(PathBuf::from(home).join(".cache").join("noctalia").join("wallpapers.json"))
    }

    fn theming_config(&self) -> Option<PathBuf> {
        let home = std::env::var("HOME").ok()?;
        Some(PathBuf::from(home).join(".cache").join("noctalia").join("theming.dynamic.toml"))
    }

    fn source_files(&self) -> Vec<&'static str> {
        NOCTALIA_FILES.to_vec()
    }

    fn rendered_color_files(&self) -> Vec<&'static str> {
        NOCTALIA_RENDERED_FILES.to_vec()
    }

    fn template_processor(&self) -> Option<PathBuf> {
        if let Ok(path) = std::env::var("HVE_NOCTALIA_TEMPLATE_PROCESSOR") {
            let p = PathBuf::from(path);
            if p.exists() {
                return Some(p);
            }
        }
        let candidates = [
            "/etc/xdg/quickshell/noctalia-shell/Scripts/python/src/theming/template-processor.py",
        ];
        for c in &candidates {
            let p = PathBuf::from(c);
            if p.exists() {
                return Some(p);
            }
        }
        None
    }

    fn reload_command(&self) -> Vec<String> {
        vec!["hyprctl".into(), "reload".into()]
    }

    /// Apply a wallpaper to a specific screen via Quickshell IPC.
    fn apply_wallpaper(&self, path: &Path, screen: &str) -> Result<(), String> {
        let path_str = path.to_str().ok_or("Invalid wallpaper path")?;
        let output = std::process::Command::new("quickshell")
            .args(["-c", "noctalia-shell", "ipc", "call", "wallpaper", "set", path_str, screen])
            .output()
            .map_err(|e| format!("Failed to run quickshell IPC: {}", e))?;

        if output.status.success() {
            Ok(())
        } else {
            let stderr = String::from_utf8_lossy(&output.stderr);
            Err(format!("Wallpaper IPC failed: {}", stderr.trim()))
        }
    }

    /// Get the current wallpaper path for a screen via Quickshell IPC.
    fn get_wallpaper(&self, screen: &str) -> Result<String, String> {
        let output = std::process::Command::new("quickshell")
            .args(["-c", "noctalia-shell", "ipc", "call", "wallpaper", "get", screen])
            .output()
            .map_err(|e| format!("Failed to run quickshell IPC: {}", e))?;

        if output.status.success() {
            let stdout = String::from_utf8_lossy(&output.stdout);
            Ok(stdout.trim().to_string())
        } else {
            let stderr = String::from_utf8_lossy(&output.stderr);
            Err(format!("Wallpaper get failed: {}", stderr.trim()))
        }
    }
}

/// Detects whether a shell is active on the system.
pub trait ShellDetector: Send + Sync {
    // `id` is used by tests and by `ShellRegistry` (tests-only); the lint does
    // not count `#[cfg(test)]` usage during a plain `cargo check`.
    #[allow(dead_code)]
    fn id(&self) -> &str;
    fn is_active(&self) -> bool;
}

impl ShellDetector for NoctaliaV4Paths {
    fn id(&self) -> &str {
        "noctalia"
    }

    fn is_active(&self) -> bool {
        // `.output()`, never `.status()`: `status()` inherits this process's
        // stdout, so `pgrep` prints the matching PID straight into whatever
        // terminal launched HVE. The question here is only "did it match",
        // and `.output()` answers it while capturing the PID.
        std::process::Command::new("pgrep")
            .arg("-x")
            .arg("quickshell")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false)
    }
}

/// Noctalia v5 (Rust native shell) — paths for detection and palette access only.
///
/// The provider's save/apply is handled entirely over IPC (`noctalia msg`).
/// There is no template processor, rendered files, wallpapers.json cache, or reload.
/// v5 has automatic hot-reload.
pub struct NoctaliaV5Paths;

impl ShellProvider for NoctaliaV5Paths {
    fn id(&self) -> &str {
        "noctalia"
    }

    fn display_name(&self) -> &str {
        "Noctalia v5"
    }

    fn config_dir(&self) -> Option<PathBuf> {
        if let Ok(dir) = std::env::var("HVE_NOCTALIA_CONFIG") {
            let p = PathBuf::from(dir);
            if p.exists() {
                return Some(p);
            }
        }
        dirs::config_dir().map(|d| d.join("noctalia"))
    }

    fn rendered_dir(&self) -> Option<PathBuf> {
        None
    }

    fn wallpapers_file(&self) -> Option<PathBuf> {
        None
    }

    fn theming_config(&self) -> Option<PathBuf> {
        None
    }

    fn source_files(&self) -> Vec<&'static str> {
        Vec::new()
    }

    fn rendered_color_files(&self) -> Vec<&'static str> {
        Vec::new()
    }

    fn template_processor(&self) -> Option<PathBuf> {
        None
    }

    fn reload_command(&self) -> Vec<String> {
        Vec::new()
    }

    fn apply_wallpaper(&self, path: &Path, screen: &str) -> Result<(), String> {
        let path_str = path.to_str().ok_or("Invalid wallpaper path")?;
        let output = std::process::Command::new("noctalia")
            .args(["msg", "wallpaper-set", screen, path_str])
            .output()
            .map_err(|e| format!("Failed to run noctalia msg: {}", e))?;

        if output.status.success() {
            Ok(())
        } else {
            let stderr = String::from_utf8_lossy(&output.stderr);
            Err(format!("Wallpaper IPC failed: {}", stderr.trim()))
        }
    }

    fn get_wallpaper(&self, screen: &str) -> Result<String, String> {
        let output = std::process::Command::new("noctalia")
            .args(["msg", "wallpaper-get", screen])
            .output()
            .map_err(|e| format!("Failed to run noctalia msg: {}", e))?;

        if output.status.success() {
            let stdout = String::from_utf8_lossy(&output.stdout);
            Ok(stdout.trim().to_string())
        } else {
            let stderr = String::from_utf8_lossy(&output.stderr);
            Err(format!("Wallpaper get failed: {}", stderr.trim()))
        }
    }
}

impl ShellDetector for NoctaliaV5Paths {
    fn id(&self) -> &str {
        "noctalia"
    }

    fn is_active(&self) -> bool {
        // Both conditions are required:
        // 1. The noctalia process is running
        // 2. ~/.config/noctalia/profiles/ exists (v5 only)
        // Same rule as the v4 detector above: `.output()` captures the PID
        // `pgrep` would otherwise print into HVE's own terminal.
        let process_running = std::process::Command::new("pgrep")
            .arg("-x")
            .arg("noctalia")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false);

        let profiles_dir_exists = self
            .config_dir()
            .map(|c| c.join("profiles").exists())
            .unwrap_or(false);

        process_running && profiles_dir_exists
    }
}

/// Registry that detects which shell is active.
///
/// Detectors are registered in order; the first one to return
/// `is_active() == true` is marked as active.
///
/// NOTE: only instantiated by tests. Production (main.rs) bypasses the
/// registry and calls `is_active()` on the detectors directly.
#[allow(dead_code)]
pub struct ShellRegistry {
    detectors: Vec<Box<dyn ShellDetector>>,
    active_id: Option<String>,
}

#[allow(dead_code)]
impl ShellRegistry {
    pub fn new() -> Self {
        Self {
            detectors: Vec::new(),
            active_id: None,
        }
    }

    pub fn register<T: ShellDetector + 'static>(&mut self, detector: T) {
        let id = detector.id().to_string();
        if self.active_id.is_none() && detector.is_active() {
            tracing::info!("[shell] {} detectado como activo", id);
            self.active_id = Some(id.clone());
        }
        self.detectors.push(Box::new(detector));
    }

    pub fn active_id(&self) -> Option<&str> {
        self.active_id.as_deref()
    }

    pub fn is_active(&self, id: &str) -> bool {
        self.active_id.as_deref() == Some(id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn test_noctalia_v4_paths_id() {
        let p = NoctaliaV4Paths;
        assert_eq!(<NoctaliaV4Paths as ShellProvider>::id(&p), "noctalia");
    }

    #[test]
    fn test_noctalia_v4_paths_display_name() {
        let p = NoctaliaV4Paths;
        assert_eq!(p.display_name(), "Noctalia v4");
    }

    #[test]
    fn test_noctalia_v4_paths_wallpapers_file() {
        let _env = crate::test_utils::env_guard();
        let p = NoctaliaV4Paths;
        let wf = p.wallpapers_file();
        assert!(wf.is_some());
        let wf = wf.unwrap();
        assert!(wf.ends_with("wallpapers.json"));
        assert!(wf.parent().unwrap().ends_with(".cache/noctalia"));
    }

    #[test]
    fn test_noctalia_v4_paths_theming_config() {
        let _env = crate::test_utils::env_guard();
        let p = NoctaliaV4Paths;
        let tc = p.theming_config();
        assert!(tc.is_some());
        let tc = tc.unwrap();
        assert!(tc.ends_with("theming.dynamic.toml"));
        assert!(tc.parent().unwrap().ends_with(".cache/noctalia"));
    }

    #[test]
    fn test_noctalia_v4_paths_reload_command() {
        let p = NoctaliaV4Paths;
        let cmd = p.reload_command();
        assert_eq!(cmd, vec!["hyprctl".to_string(), "reload".to_string()]);
    }

    #[test]
    fn test_source_files() {
        let p = NoctaliaV4Paths;
        let files = p.source_files();
        assert!(files.contains(&"settings.json"));
        assert!(files.contains(&"colors.json"));
        assert!(files.contains(&"plugins.json"));
    }

    #[test]
    fn test_rendered_color_files() {
        let p = NoctaliaV4Paths;
        let files = p.rendered_color_files();
        assert!(files.contains(&"noctalia-colors.conf"));
        assert!(files.contains(&"noctalia-colors.lua"));
    }

    #[test]
    fn test_apply_wallpaper_ipc_format() {
        let _env = crate::test_utils::env_guard();
        let p = NoctaliaV4Paths;
        let result = p.apply_wallpaper(Path::new("/tmp/fake.png"), "DP-3");
        // It can fail if quickshell is not available or returns an error
        // We only check that it does not panic and that the command syntax is correct
        if let Err(e) = &result {
            assert!(
                e.contains("quickshell") || e.contains("Wallpaper IPC"),
                "unexpected error: {}",
                e
            );
        }
    }

    #[test]
    fn test_get_wallpaper_ipc_format() {
        let _env = crate::test_utils::env_guard();
        let p = NoctaliaV4Paths;
        let result = p.get_wallpaper("DP-3");
        if let Err(e) = &result {
            assert!(
                e.contains("quickshell") || e.contains("Wallpaper get"),
                "unexpected error: {}",
                e
            );
        }
    }

    // ── NoctaliaV5Paths tests ──

    #[test]
    fn test_noctalia_v5_paths_id() {
        let p = NoctaliaV5Paths;
        assert_eq!(<NoctaliaV5Paths as ShellProvider>::id(&p), "noctalia");
    }

    #[test]
    fn test_noctalia_v5_paths_display_name() {
        let p = NoctaliaV5Paths;
        assert_eq!(p.display_name(), "Noctalia v5");
    }

    #[test]
    fn test_noctalia_v5_paths_config_dir() {
        let _env = crate::test_utils::env_guard();
        let p = NoctaliaV5Paths;
        let cd = p.config_dir();
        assert!(cd.is_some());
        let cd = cd.unwrap();
        assert!(cd.ends_with("noctalia"));
    }

    #[test]
    fn test_noctalia_v5_paths_rendered_dir_none() {
        let _env = crate::test_utils::env_guard();
        let p = NoctaliaV5Paths;
        assert!(p.rendered_dir().is_none());
    }

    #[test]
    fn test_noctalia_v5_paths_theming_config_none() {
        let p = NoctaliaV5Paths;
        assert!(p.theming_config().is_none());
    }

    #[test]
    fn test_noctalia_v5_paths_template_processor_none() {
        let p = NoctaliaV5Paths;
        assert!(p.template_processor().is_none());
    }

    #[test]
    fn test_noctalia_v5_paths_wallpapers_file_none() {
        let p = NoctaliaV5Paths;
        assert!(p.wallpapers_file().is_none());
    }

    #[test]
    fn test_noctalia_v5_paths_source_files_empty() {
        let p = NoctaliaV5Paths;
        assert!(p.source_files().is_empty());
    }

    #[test]
    fn test_noctalia_v5_paths_rendered_color_files_empty() {
        let p = NoctaliaV5Paths;
        assert!(p.rendered_color_files().is_empty());
    }

    #[test]
    fn test_noctalia_v5_paths_reload_command_empty() {
        let p = NoctaliaV5Paths;
        assert!(p.reload_command().is_empty());
    }

    #[test]
    fn test_noctalia_v5_paths_apply_wallpaper_ipc_format() {
        let _env = crate::test_utils::env_guard();
        let p = NoctaliaV5Paths;
        // It can fail — we only check that it does not panic and the syntax is correct
        let result = p.apply_wallpaper(Path::new("/tmp/fake.png"), "DP-3");
        if let Err(e) = &result {
            assert!(
                e.contains("noctalia") || e.contains("Wallpaper IPC") || e.contains("No such file"),
                "unexpected error: {}",
                e
            );
        }
    }

    #[test]
    fn test_noctalia_v5_paths_get_wallpaper_ipc_format() {
        let _env = crate::test_utils::env_guard();
        let p = NoctaliaV5Paths;
        let result = p.get_wallpaper("DP-3");
        if let Err(e) = &result {
            assert!(
                e.contains("noctalia") || e.contains("Wallpaper get") || e.contains("No such file"),
                "unexpected error: {}",
                e
            );
        }
    }

    // ── ShellDetector tests ──

    #[test]
    fn test_v4_detector_id() {
        let detector = NoctaliaV4Paths;
        assert_eq!(<NoctaliaV4Paths as ShellDetector>::id(&detector), "noctalia");
    }

    #[test]
    fn test_v5_detector_id() {
        let detector = NoctaliaV5Paths;
        assert_eq!(<NoctaliaV5Paths as ShellDetector>::id(&detector), "noctalia");
    }

    #[test]
    fn test_v4_detector_is_active_no_crash() {
        // It can be true or false depending on whether quickshell is running
        // We only check that it does not panic
        let _env = crate::test_utils::env_guard();
        let detector = NoctaliaV4Paths;
        let _ = detector.is_active();
    }

    #[test]
    fn test_v5_detector_is_active_no_crash() {
        // It can be true or false depending on processes and directories
        // We only check that it does not panic
        let _env = crate::test_utils::env_guard();
        let detector = NoctaliaV5Paths;
        let _ = detector.is_active();
    }

    // ── ShellRegistry tests ──

    #[test]
    fn test_registry_new_empty() {
        let registry = ShellRegistry::new();
        assert!(registry.active_id().is_none());
    }

    #[test]
    fn test_registry_register_v4_v5() {
        let _env = crate::test_utils::env_guard();
        let mut registry = ShellRegistry::new();
        registry.register(NoctaliaV4Paths);
        registry.register(NoctaliaV5Paths);
        // active_id will be None (no process running in tests)
        // or Some("noctalia") (if one of the detectors returns true)
        match registry.active_id() {
            None => {} // none active — OK
            Some(id) => assert_eq!(id, "noctalia"), // one active — OK
        }
    }

    #[test]
    fn test_registry_is_active_check() {
        let _env = crate::test_utils::env_guard();
        let mut registry = ShellRegistry::new();
        registry.register(NoctaliaV4Paths);
        registry.register(NoctaliaV5Paths);

        // If any is active, is_active("noctalia") must be true
        if registry.active_id() == Some("noctalia") {
            assert!(registry.is_active("noctalia"));
            assert!(!registry.is_active("nonexistent"));
        } else {
            assert!(!registry.is_active("noctalia"));
        }
    }
}
