use crate::theme_manager::ThemeProvider;
use std::fs;
use std::path::{Path, PathBuf};

/// Noctalia config directory: ~/.config/noctalia/
fn noctalia_config_dir() -> Option<PathBuf> {
    dirs::config_dir()
        .or_else(|| {
            let home = std::env::var("HOME").ok()?;
            Some(PathBuf::from(home).join(".config"))
        })
        .map(|d| d.join("noctalia"))
}

/// Noctalia rendered color files directory: ~/.config/hypr/noctalia/
fn noctalia_hypr_dir() -> Option<PathBuf> {
    let home = std::env::var("HOME").ok()?;
    Some(PathBuf::from(home).join(".config").join("hypr").join("noctalia"))
}

/// Source config files we snapshot for Noctalia.
const NOCTALIA_FILES: &[&str] = &["settings.json", "colors.json", "plugins.json"];

/// Rendered color files generated by Noctalia in the Hyprland config dir.
/// These are what `colors.sh` actually reads, and what Hyprland sources.
const NOCTALIA_RENDERED_FILES: &[&str] = &["noctalia-colors.conf", "noctalia-colors.lua"];

/// Strip leading `#` from a hex color if present, returning the raw hex digits.
fn strip_hash(hex: &str) -> &str {
    hex.trim_start_matches('#')
}

/// Convert `#RRGGBB` to `rgb(RRGGBB)` format (no hash).
fn to_rgb_func(hex: &str) -> String {
    format!("rgb({})", strip_hash(hex))
}

/// Darken a hex color by reducing luminance (simple per-channel scaling).
fn darken_hex(hex: &str, factor: f32) -> String {
    let h = strip_hash(hex);
    if h.len() != 6 {
        return hex.to_string();
    }
    let r = (u8::from_str_radix(&h[0..2], 16).unwrap_or(0) as f32 * (1.0 - factor)) as u8;
    let g = (u8::from_str_radix(&h[2..4], 16).unwrap_or(0) as f32 * (1.0 - factor)) as u8;
    let b = (u8::from_str_radix(&h[4..6], 16).unwrap_or(0) as f32 * (1.0 - factor)) as u8;
    format!("#{:02x}{:02x}{:02x}", r, g, b)
}

/// Generate `noctalia-colors.conf` content from a colors.json-style value map.
fn generate_conf_content(colors: &serde_json::Map<String, serde_json::Value>) -> String {
    let primary = colors.get("mPrimary").and_then(|v| v.as_str()).unwrap_or("#cba6f7");
    let secondary = colors.get("mSecondary").and_then(|v| v.as_str()).unwrap_or("#89b4fa");
    let tertiary = colors.get("mTertiary").and_then(|v| v.as_str()).unwrap_or("#89b4fa");
    let surface = colors.get("mSurface").and_then(|v| v.as_str()).unwrap_or("#1e1e2e");
    let error = colors.get("mError").and_then(|v| v.as_str()).unwrap_or("#f7768e");
    // surface_lowest: prefer mShadow if it exists and is different from mSurface, else darken surface
    let shadow = colors.get("mShadow").and_then(|v| v.as_str());
    let surface_lowest = shadow
        .filter(|s| *s != surface)
        .map(|s| s.to_string())
        .unwrap_or_else(|| darken_hex(surface, 0.08));

    format!(
        concat!(
            "$primary = {}\n",
            "$surface = {}\n",
            "$secondary = {}\n",
            "$error = {}\n",
            "$tertiary = {}\n",
            "$surface_lowest = {}\n",
        ),
        to_rgb_func(primary),
        to_rgb_func(surface),
        to_rgb_func(secondary),
        to_rgb_func(error),
        to_rgb_func(tertiary),
        to_rgb_func(&surface_lowest),
    )
}

/// Generate `noctalia-colors.lua` content from a colors.json-style value map.
fn generate_lua_content(colors: &serde_json::Map<String, serde_json::Value>) -> String {
    let primary = colors.get("mPrimary").and_then(|v| v.as_str()).unwrap_or("#cba6f7");
    let secondary = colors.get("mSecondary").and_then(|v| v.as_str()).unwrap_or("#89b4fa");
    let tertiary = colors.get("mTertiary").and_then(|v| v.as_str()).unwrap_or("#89b4fa");
    let surface = colors.get("mSurface").and_then(|v| v.as_str()).unwrap_or("#1e1e2e");
    let error = colors.get("mError").and_then(|v| v.as_str()).unwrap_or("#f7768e");
    let shadow = colors.get("mShadow").and_then(|v| v.as_str());
    let surface_lowest = shadow
        .filter(|s| *s != surface)
        .map(|s| s.to_string())
        .unwrap_or_else(|| darken_hex(surface, 0.08));

    format!(
        concat!(
            "primary = \"{}\"\n",
            "surface = \"{}\"\n",
            "secondary = \"{}\"\n",
            "error = \"{}\"\n",
            "tertiary = \"{}\"\n",
            "surface_lowest = \"{}\"\n",
        ),
        to_rgb_func(primary),
        to_rgb_func(surface),
        to_rgb_func(secondary),
        to_rgb_func(error),
        to_rgb_func(tertiary),
        to_rgb_func(&surface_lowest),
    )
}

/// Fallback: read `colors.json` and generate the rendered files on the fly.
/// This handles themes saved before we started snapshotting rendered files.
fn generate_rendered_from_colors_json(provider_dir: &Path) -> Result<(), String> {
    let colors_path = provider_dir.join("colors.json");
    if !colors_path.exists() {
        return Err("No colors.json in theme to generate rendered files".into());
    }

    let raw = fs::read_to_string(&colors_path)
        .map_err(|e| format!("Cannot read colors.json: {}", e))?;
    let parsed: serde_json::Value = serde_json::from_str(&raw)
        .map_err(|e| format!("Cannot parse colors.json: {}", e))?;

    let map = match parsed.as_object() {
        Some(m) => m,
        None => return Err("colors.json is not a JSON object".into()),
    };

    let conf = generate_conf_content(map);
    let lua = generate_lua_content(map);

    fs::write(provider_dir.join("noctalia-colors.conf"), &conf)
        .map_err(|e| format!("Cannot write noctalia-colors.conf: {}", e))?;
    fs::write(provider_dir.join("noctalia-colors.lua"), &lua)
        .map_err(|e| format!("Cannot write noctalia-colors.lua: {}", e))?;

    Ok(())
}

pub struct NoctaliaProvider;

impl ThemeProvider for NoctaliaProvider {
    fn id(&self) -> &str {
        "noctalia"
    }

    fn display_name_key(&self) -> &str {
        "themes.provider.noctalia"
    }

    fn icon(&self) -> &str {
        "◈"
    }

    fn save(&self, theme_dir: &Path) -> Result<(), String> {
        let src = noctalia_config_dir().ok_or("Noctalia config dir not found")?;
        let hypr_src = noctalia_hypr_dir().ok_or("Noctalia hypr dir not found")?;

        let provider_dir = theme_dir.join("providers").join(self.id());
        fs::create_dir_all(&provider_dir)
            .map_err(|e| format!("Cannot create provider dir: {}", e))?;

        // Save source config files
        for file in NOCTALIA_FILES {
            let src_path = src.join(file);
            if src_path.exists() {
                let dst_path = provider_dir.join(file);
                fs::copy(&src_path, &dst_path)
                    .map_err(|e| format!("Cannot copy {}: {}", file, e))?;
            }
        }

        // Save rendered color files so apply can restore them directly
        // without needing Noctalia to regenerate them.
        for file in NOCTALIA_RENDERED_FILES {
            let src_path = hypr_src.join(file);
            if src_path.exists() {
                let dst_path = provider_dir.join(file);
                fs::copy(&src_path, &dst_path)
                    .map_err(|e| format!("Cannot copy {}: {}", file, e))?;
            }
        }

        Ok(())
    }

    fn apply(&self, theme_dir: &Path) -> Result<(), String> {
        let dst = noctalia_config_dir().ok_or("Noctalia config dir not found")?;
        let hypr_dst = noctalia_hypr_dir().ok_or("Noctalia hypr dir not found")?;
        let provider_dir = theme_dir.join("providers").join(self.id());

        if !provider_dir.exists() {
            return Err("Noctalia provider data not found in theme".into());
        }

        // Step 1: Restore source config files (Noctalia app state)
        for file in NOCTALIA_FILES {
            let src_path = provider_dir.join(file);
            if src_path.exists() {
                let dst_path = dst.join(file);
                let tmp = dst_path.with_extension("json.noctalia-tmp");
                fs::copy(&src_path, &tmp)
                    .map_err(|e| format!("Cannot copy {}: {}", file, e))?;
                fs::rename(&tmp, &dst_path)
                    .map_err(|e| format!("Cannot rename {}: {}", file, e))?;
            }
        }

        // Step 2: Ensure rendered color files exist in the provider directory.
        // New-style themes have them saved directly.
        // Old-style themes (pre-patch) only have colors.json — generate from there.
        let has_conf = provider_dir.join("noctalia-colors.conf").exists();
        let has_lua = provider_dir.join("noctalia-colors.lua").exists();
        if !has_conf || !has_lua {
            generate_rendered_from_colors_json(&provider_dir)?;
        }

        // Step 3: Restore rendered color files to the Hyprland config dir
        fs::create_dir_all(&hypr_dst)
            .map_err(|e| format!("Cannot create hypr noctalia dir: {}", e))?;
        for file in NOCTALIA_RENDERED_FILES {
            let src_path = provider_dir.join(file);
            if src_path.exists() {
                let dst_path = hypr_dst.join(file);
                let tmp = hypr_dst.join(format!("{}.tmp", file));
                fs::copy(&src_path, &tmp)
                    .map_err(|e| format!("Cannot copy {}: {}", file, e))?;
                fs::rename(&tmp, &dst_path)
                    .map_err(|e| format!("Cannot rename {}: {}", file, e))?;
            }
        }

        // Step 4: Reload Hyprland so it picks up the restored colors
        let _ = std::process::Command::new("hyprctl")
            .arg("reload")
            .output();

        Ok(())
    }

    fn post_apply(&self, theme_name: &str) -> Result<(), String> {
        let home = match std::env::var("HOME") {
            Ok(h) => h,
            Err(_) => return Ok(()),
        };

        // ── Step 1: Run Noctalia template processor ──
        // Regenerates GTK, QT, terminal, VSCode, Zen, btop, yazi themes from colors.json.
        // Each shell knows its own post-apply mechanism — this is Noctalia v4's.
        let template_processor = Path::new(
            "/etc/xdg/quickshell/noctalia-shell/Scripts/python/src/theming/template-processor.py",
        );
        let noctalia_colors = noctalia_config_dir()
            .unwrap_or_else(|| Path::new(&home).join(".config").join("noctalia"))
            .join("colors.json");
        let theming_config =
            Path::new(&home).join(".cache").join("noctalia").join("theming.dynamic.toml");

        if template_processor.exists() && noctalia_colors.exists() && theming_config.exists() {
            tracing::info!("[noctalia] Running template processor to refresh system themes...");
            let processor_dir = template_processor
                .parent()
                .unwrap_or_else(|| Path::new("/"));
            match std::process::Command::new("python3")
                .arg(template_processor)
                .arg(&noctalia_colors)
                .arg("--scheme")
                .arg(&noctalia_colors)
                .arg("-c")
                .arg(&theming_config)
                .current_dir(processor_dir)
                .output()
            {
                Ok(output) => {
                    if !output.status.success() {
                        let stderr = String::from_utf8_lossy(&output.stderr);
                        tracing::warn!("[noctalia] Template processor stderr: {}", stderr);
                    } else {
                        tracing::info!("[noctalia] Template processor completed successfully");
                    }
                }
                Err(e) => {
                    tracing::warn!("[noctalia] Could not launch template processor: {}", e);
                }
            }
        }

        // ── Step 2: System notification ──
        // Portable across desktop environments, unlike Quickshell's ToastService.
        match std::process::Command::new("notify-send")
            .arg("--app-name=HVE")
            .arg(format!("🎨 Tema '{}' aplicado", theme_name))
            .arg(format!(
                "Theme \"{}\" applied — colors synced to GTK, QT, terminal, and apps",
                theme_name,
            ))
            .output()
        {
            Ok(_) => {}
            Err(e) => {
                tracing::warn!("[noctalia] notify-send not available: {}", e);
            }
        }

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_conf_content() {
        let mut map = serde_json::Map::new();
        map.insert("mPrimary".into(), serde_json::Value::String("#2ec436".into()));
        map.insert("mSecondary".into(), serde_json::Value::String("#fb9e0f".into()));
        map.insert("mTertiary".into(), serde_json::Value::String("#9d00ff".into()));
        map.insert("mSurface".into(), serde_json::Value::String("#0c1017".into()));
        map.insert("mError".into(), serde_json::Value::String("#b32d2d".into()));
        map.insert("mShadow".into(), serde_json::Value::String("#090d13".into()));

        let conf = generate_conf_content(&map);
        assert!(conf.contains("$primary = rgb(2ec436)"));
        assert!(conf.contains("$surface = rgb(0c1017)"));
        assert!(conf.contains("$secondary = rgb(fb9e0f)"));
        assert!(conf.contains("$error = rgb(b32d2d)"));
        assert!(conf.contains("$tertiary = rgb(9d00ff)"));
        assert!(conf.contains("$surface_lowest = rgb(090d13)"));
    }

    #[test]
    fn test_generate_lua_content() {
        let mut map = serde_json::Map::new();
        map.insert("mPrimary".into(), serde_json::Value::String("#2ec436".into()));
        map.insert("mSecondary".into(), serde_json::Value::String("#fb9e0f".into()));
        map.insert("mTertiary".into(), serde_json::Value::String("#9d00ff".into()));
        map.insert("mSurface".into(), serde_json::Value::String("#0c1017".into()));
        map.insert("mError".into(), serde_json::Value::String("#b32d2d".into()));
        map.insert("mShadow".into(), serde_json::Value::String("#090d13".into()));

        let lua = generate_lua_content(&map);
        assert!(lua.contains("primary = \"rgb(2ec436)\""));
        assert!(lua.contains("surface = \"rgb(0c1017)\""));
        assert!(lua.contains("secondary = \"rgb(fb9e0f)\""));
        assert!(lua.contains("error = \"rgb(b32d2d)\""));
        assert!(lua.contains("tertiary = \"rgb(9d00ff)\""));
        assert!(lua.contains("surface_lowest = \"rgb(090d13)\""));
    }

    #[test]
    fn test_generate_fallback_no_shadow() {
        let mut map = serde_json::Map::new();
        map.insert("mPrimary".into(), serde_json::Value::String("#2ec436".into()));
        map.insert("mSurface".into(), serde_json::Value::String("#0c1017".into()));
        // No mShadow — should darken surface as fallback

        let conf = generate_conf_content(&map);
        assert!(conf.contains("$surface_lowest"));
        // Darkened #0c1017 by 0.08 should be #0b0e15 (approx)
        assert!(conf.contains("rgb(0b0e15)") || conf.contains("rgb(0b0f15)") || conf.contains("rgb(0b0e14)") || conf.contains("rgb(0b0f14)"));
    }

    #[test]
    fn test_to_rgb_func() {
        assert_eq!(to_rgb_func("#2ec436"), "rgb(2ec436)");
        assert_eq!(to_rgb_func("2ec436"), "rgb(2ec436)");
    }

    #[test]
    fn test_darken_hex() {
        let darkened = darken_hex("#0c1017", 0.08);
        assert_ne!(darkened, "#0c1017");
        assert!(darkened.starts_with('#'));
        assert_eq!(darkened.len(), 7);
    }
}
