use std::path::{Path, PathBuf};

/// A shell knows how to resolve its configuration paths and perform shell-specific
/// operations like wallpaper IPC.
///
/// This replaces the old `ShellPaths` trait with a richer interface that
/// includes source/rendered file lists, template processor paths, and
/// wallpaper IPC operations.
pub trait ShellProvider: Send + Sync {
    #[allow(dead_code)]
    fn id(&self) -> &str;
    #[allow(dead_code)]
    fn display_name(&self) -> &str;
    #[allow(dead_code)]
    fn config_dir(&self) -> Option<PathBuf>;
    #[allow(dead_code)]
    fn rendered_dir(&self) -> Option<PathBuf>;
    #[allow(dead_code)]
    fn wallpapers_file(&self) -> Option<PathBuf>;
    #[allow(dead_code)]
    fn theming_config(&self) -> Option<PathBuf>;
    fn source_files(&self) -> Vec<&'static str>;
    fn rendered_color_files(&self) -> Vec<&'static str>;
    #[allow(dead_code)]
    fn template_processor(&self) -> Option<PathBuf>;
    #[allow(dead_code)]
    fn reload_command(&self) -> Vec<String>;
    #[allow(dead_code, unused_variables)]
    fn apply_wallpaper(&self, path: &Path, screen: &str) -> Result<(), String> {
        Ok(())
    }
    #[allow(dead_code, unused_variables)]
    fn get_wallpaper(&self, screen: &str) -> Result<String, String> {
        Err("not supported".into())
    }
}

/// Source config files we snapshot for Noctalia.
const NOCTALIA_FILES: &[&str] = &["settings.json", "colors.json", "plugins.json"];

/// Rendered color files generated by Noctalia in the Hyprland config dir.
/// These are what `colors.sh` actually reads, and what Hyprland sources.
const NOCTALIA_RENDERED_FILES: &[&str] = &["noctalia-colors.conf", "noctalia-colors.lua"];

/// Rutas por defecto para Noctalia v4.
///
/// Soporta tres niveles de personalización (prioridad descendente):
/// 1. Environment variables: `HVE_NOCTALIA_CONFIG`, `HVE_NOCTALIA_HYPR`,
///    `HVE_NOCTALIA_TEMPLATE_PROCESSOR`
/// 2. System paths: `/etc/xdg/quickshell/noctalia-shell/...`
/// 3. Standard locations: `dirs::config_dir()`, `~/.config/...`
pub struct NoctaliaV4Paths;

impl ShellProvider for NoctaliaV4Paths {
    fn id(&self) -> &str {
        "noctalia"
    }

    fn display_name(&self) -> &str {
        "Noctalia v4"
    }

    fn config_dir(&self) -> Option<PathBuf> {
        if let Ok(dir) = std::env::var("HVE_NOCTALIA_CONFIG") {
            let p = PathBuf::from(dir);
            if p.exists() {
                return Some(p);
            }
        }
        dirs::config_dir().map(|d| d.join("noctalia"))
    }

    fn rendered_dir(&self) -> Option<PathBuf> {
        if let Ok(dir) = std::env::var("HVE_NOCTALIA_HYPR") {
            let p = PathBuf::from(dir);
            if p.exists() {
                return Some(p);
            }
        }
        dirs::home_dir().map(|d| d.join(".config").join("hypr").join("noctalia"))
    }

    fn wallpapers_file(&self) -> Option<PathBuf> {
        let home = std::env::var("HOME").ok()?;
        Some(PathBuf::from(home).join(".cache").join("noctalia").join("wallpapers.json"))
    }

    fn theming_config(&self) -> Option<PathBuf> {
        let home = std::env::var("HOME").ok()?;
        Some(PathBuf::from(home).join(".cache").join("noctalia").join("theming.dynamic.toml"))
    }

    fn source_files(&self) -> Vec<&'static str> {
        NOCTALIA_FILES.to_vec()
    }

    fn rendered_color_files(&self) -> Vec<&'static str> {
        NOCTALIA_RENDERED_FILES.to_vec()
    }

    fn template_processor(&self) -> Option<PathBuf> {
        if let Ok(path) = std::env::var("HVE_NOCTALIA_TEMPLATE_PROCESSOR") {
            let p = PathBuf::from(path);
            if p.exists() {
                return Some(p);
            }
        }
        let candidates = [
            "/etc/xdg/quickshell/noctalia-shell/Scripts/python/src/theming/template-processor.py",
        ];
        for c in &candidates {
            let p = PathBuf::from(c);
            if p.exists() {
                return Some(p);
            }
        }
        None
    }

    fn reload_command(&self) -> Vec<String> {
        vec!["hyprctl".into(), "reload".into()]
    }

    /// Apply a wallpaper to a specific screen via Quickshell IPC.
    fn apply_wallpaper(&self, path: &Path, screen: &str) -> Result<(), String> {
        let path_str = path.to_str().ok_or("Invalid wallpaper path")?;
        let output = std::process::Command::new("quickshell")
            .args(["-c", "noctalia-shell", "ipc", "call", "wallpaper", "set", path_str, screen])
            .output()
            .map_err(|e| format!("Failed to run quickshell IPC: {}", e))?;

        if output.status.success() {
            Ok(())
        } else {
            let stderr = String::from_utf8_lossy(&output.stderr);
            Err(format!("Wallpaper IPC failed: {}", stderr.trim()))
        }
    }

    /// Get the current wallpaper path for a screen via Quickshell IPC.
    fn get_wallpaper(&self, screen: &str) -> Result<String, String> {
        let output = std::process::Command::new("quickshell")
            .args(["-c", "noctalia-shell", "ipc", "call", "wallpaper", "get", screen])
            .output()
            .map_err(|e| format!("Failed to run quickshell IPC: {}", e))?;

        if output.status.success() {
            let stdout = String::from_utf8_lossy(&output.stdout);
            Ok(stdout.trim().to_string())
        } else {
            let stderr = String::from_utf8_lossy(&output.stderr);
            Err(format!("Wallpaper get failed: {}", stderr.trim()))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn test_noctalia_v4_paths_id() {
        let p = NoctaliaV4Paths;
        assert_eq!(p.id(), "noctalia");
    }

    #[test]
    fn test_noctalia_v4_paths_display_name() {
        let p = NoctaliaV4Paths;
        assert_eq!(p.display_name(), "Noctalia v4");
    }

    #[test]
    fn test_noctalia_v4_paths_wallpapers_file() {
        let p = NoctaliaV4Paths;
        let wf = p.wallpapers_file();
        assert!(wf.is_some());
        let wf = wf.unwrap();
        assert!(wf.ends_with("wallpapers.json"));
        assert!(wf.parent().unwrap().ends_with(".cache/noctalia"));
    }

    #[test]
    fn test_noctalia_v4_paths_theming_config() {
        let p = NoctaliaV4Paths;
        let tc = p.theming_config();
        assert!(tc.is_some());
        let tc = tc.unwrap();
        assert!(tc.ends_with("theming.dynamic.toml"));
        assert!(tc.parent().unwrap().ends_with(".cache/noctalia"));
    }

    #[test]
    fn test_noctalia_v4_paths_reload_command() {
        let p = NoctaliaV4Paths;
        let cmd = p.reload_command();
        assert_eq!(cmd, vec!["hyprctl".to_string(), "reload".to_string()]);
    }

    #[test]
    fn test_source_files() {
        let p = NoctaliaV4Paths;
        let files = p.source_files();
        assert!(files.contains(&"settings.json"));
        assert!(files.contains(&"colors.json"));
        assert!(files.contains(&"plugins.json"));
    }

    #[test]
    fn test_rendered_color_files() {
        let p = NoctaliaV4Paths;
        let files = p.rendered_color_files();
        assert!(files.contains(&"noctalia-colors.conf"));
        assert!(files.contains(&"noctalia-colors.lua"));
    }

    #[test]
    fn test_apply_wallpaper_ipc_format() {
        let p = NoctaliaV4Paths;
        let result = p.apply_wallpaper(Path::new("/tmp/fake.png"), "DP-3");
        assert!(
            result.is_ok() || result.as_ref().unwrap_err().contains("quickshell"),
            "expected IPC call to be made, got: {:?}",
            result
        );
    }

    #[test]
    fn test_get_wallpaper_ipc_format() {
        let p = NoctaliaV4Paths;
        let result = p.get_wallpaper("DP-3");
        assert!(
            result.is_ok() || result.as_ref().unwrap_err().contains("quickshell") || result.as_ref().unwrap_err().contains("/tmp"),
            "expected IPC call to be made, got: {:?}",
            result
        );
    }
}
