use crate::config::{hve_cache_dir, hve_settings_path};
use crate::config_markers::{
    LUA_AUTOSTART_END, LUA_AUTOSTART_START, LUA_GENERATED_END, LUA_GENERATED_START,
    LUA_KEYBINDS_END, LUA_KEYBINDS_START, LUA_WINDOW_RULES_END, LUA_WINDOW_RULES_START,
};
use std::path::PathBuf;

/// Reload Hyprland after a settings write.
///
/// Production routes the `reload-config` capability through the registered
/// composer: a settings change is only meaningful once the compositor
/// re-reads the file. The `None` arm keeps the pre-seam spawn so a missing
/// controller can never become a silent no-op — every writer in this module
/// runs after `composer::init_global` (the startup keybind/autostart/rules
/// writes follow the composition root; the UI callbacks run on the event
/// loop, which starts after it), but the old behaviour must not depend on
/// that ordering staying true.
///
/// Under `cfg(test)` this is a deliberate no-op. The suite has no compositor
/// to reload, and a real `hyprctl reload` from a test drives the developer's
/// LIVE desktop — it re-reads their real config, re-floats HVE and drops a
/// pending fullscreen launch. The file write that precedes it (the behaviour
/// these settings functions are actually about) is untouched, and no test
/// observes the reload: it is unobservable in-process by construction, so
/// skipping it removes a harmful outside-the-repo side effect without
/// weakening any assertion.
fn reload_hyprland() {
    #[cfg(not(test))]
    {
        match crate::composer::global_controller() {
            Some(ctrl) => ctrl.composer().reload_config(),
            None => crate::composer::reload_config_detached(),
        }
    }
}

/// Pure: the auto-generated header block that sits at the top of every HVE
/// settings file. Tells Hyprland (and any human peeking at the file) that it is
/// machine-owned and derived from `~/.config/hve/config.json`.
fn generated_header_block() -> String {
    format!(
        "{LUA_GENERATED_START}\n\
-- This file is AUTO-GENERATED by HVE from ~/.config/hve/config.json.\n\
-- Do not edit by hand -- HVE rewrites it on every startup and on each change.\n\
{LUA_GENERATED_END}"
    )
}

/// Ensure the Lua settings file exists with empty window rules, keybinds and
/// autostart sections.
///
/// HVE manages its own window state via the Composer trait (fullscreen for
/// Gallery, floating for settings), so no window rules are needed.
/// Called once at startup. Creates the file with the auto-generated header when
/// missing; prepends the header idempotently when the file exists without it.
/// Does NOT overwrite or erase any existing content.
pub fn ensure_settings_file() {
    let path = hve_settings_path();

    // --- migration: prepend header to existing files that lack it ---
    if path.exists() {
        match std::fs::read_to_string(&path) {
            Ok(content) if !content.contains(LUA_GENERATED_START) => {
                let migrated = format!("{}\n{}", generated_header_block(), content);
                match std::fs::write(&path, migrated) {
                    Ok(()) => tracing::info!(
                        "[settings] Prepended generated header to {}",
                        path.display()
                    ),
                    Err(e) => tracing::error!("[settings] Header prepend failed: {}", e),
                }
            }
            _ => {} // file absent or already has header — nothing to do
        }
        return;
    }

    let _ = std::fs::create_dir_all(hve_cache_dir());

    let content = format!(
        "{header}\n{window_rules}\n{LUA_KEYBINDS_START}\n{LUA_KEYBINDS_END}\n{LUA_AUTOSTART_START}\n{LUA_AUTOSTART_END}\n",
        header = generated_header_block(),
        window_rules = window_rules_block(),
    );

    match std::fs::write(&path, content) {
        Ok(_) => tracing::info!("[settings] Created at {}", path.display()),
        Err(e) => tracing::error!("[settings] Failed to create: {}", e),
    }
}

/// Apply HVE window rules to `hve-settings.lua`.
///
/// HVE manages its own window state via the Composer trait (fullscreen for
/// Gallery, floating for settings), so the emitted window-rules block is
/// always empty except for explanatory comments. The `tiling` parameter is
/// retained for call-site compatibility, but it no longer changes the output.
///
/// This file is a dedicated file separate from the overlay (which is managed
/// by assemble.sh) and is loaded AFTER the user's windowrules.lua so its
/// block wins.
///
/// Returns true when the file was rewritten (and `hyprctl reload` fired).
/// Unchanged content is a strict no-op: every reload re-floats HVE and
/// kills a pending fullscreen dispatch, so the startup path — which calls
/// this on EVERY launch — must not reload when the rules already match.
pub(crate) fn set_tiling_window_rules(tiling: bool) -> bool {
    let path = hve_settings_path();
    if !path.exists() {
        tracing::warn!("[windowrules] File not found — creating default");
        ensure_settings_file();
    }

    let content = match std::fs::read_to_string(&path) {
        Ok(c) => c,
        Err(e) => {
            tracing::error!("[windowrules] Failed to read: {}", e);
            return false;
        }
    };

    let marker_start = LUA_WINDOW_RULES_START;
    let marker_end = LUA_WINDOW_RULES_END;

    // Build the replacement block
    let rules_block = window_rules_block();

    // Steady state: same block already on disk → skip the rewrite AND the
    // reload. A reload re-floats HVE and drops any pending fullscreen.
    if !marker_block_needs_update(&content, marker_start, marker_end, &rules_block) {
        tracing::info!(
            "[windowrules] {} mode already applied — skip rewrite+reload (tile={})",
            if tiling { "TILING" } else { "FLOATING" },
            tiling,
        );
        return false;
    }

    // Replace content between markers
    let new_content = if content.contains(marker_start) {
        let mut result = String::new();
        let mut in_block = false;
        let mut replaced = false;
        for line in content.lines() {
            if line.trim() == marker_start {
                in_block = true;
                if !replaced {
                    result.push_str(&rules_block);
                    result.push('\n');
                    replaced = true;
                }
                continue;
            }
            if line.trim() == marker_end {
                in_block = false;
                continue;
            }
            if !in_block {
                result.push_str(line);
                result.push('\n');
            }
        }
        result
    } else {
        // No markers yet → append the block
        let mut result = content;
        if !result.ends_with('\n') {
            result.push('\n');
        }
        result.push('\n');
        result.push_str(&rules_block);
        result.push('\n');
        result
    };

    match std::fs::write(&path, new_content) {
        Ok(_) => {
            tracing::info!(
                "[windowrules] {} mode applied (tile={})",
                if tiling { "TILING" } else { "FLOATING" },
                tiling,
            );
            reload_hyprland();
            true
        }
        Err(e) => {
            tracing::error!("[windowrules] Failed to write: {}", e);
            false
        }
    }
}

/// Pure: the desired Lua window-rules block.
///
/// HVE manages its own window state via the Composer trait (fullscreen for
/// Gallery, floating for settings), so the block carries only comments.
/// Shared by the startup template and the compare-before-write guard so they
/// cannot drift apart.
fn window_rules_block() -> String {
    format!(
        "{LUA_WINDOW_RULES_START}\n\
-- HVE manages its own window state via the Composer trait\n\
-- (fullscreen for Gallery, floating for settings). No rules needed here.\n\
{LUA_WINDOW_RULES_END}"
    )
}

/// Pure: whether the block between `marker_start`/`marker_end` in `content`
/// differs from `desired`. Returns true when the markers are absent (append
/// path). Whitespace-normalized so semantically identical blocks skip the
/// rewrite — and with it the `hyprctl reload` that would drop fullscreen.
pub(crate) fn marker_block_needs_update(
    content: &str,
    marker_start: &str,
    marker_end: &str,
    desired: &str,
) -> bool {
    extract_marker_block(content, marker_start, marker_end).is_none_or(|current| {
        current.trim() != desired.trim()
    })
}

/// Extract the full block including both marker lines, if both markers
/// are present. The result compares directly against a desired block from
/// the `*_block` constructors (whitespace-normalized by the caller).
fn extract_marker_block(content: &str, marker_start: &str, marker_end: &str) -> Option<String> {
    let mut in_block = false;
    let mut found_start = false;
    let mut block = String::new();
    for line in content.lines() {
        if line.trim() == marker_start {
            in_block = true;
            found_start = true;
            block.push_str(line);
            block.push('\n');
            continue;
        }
        if line.trim() == marker_end {
            if found_start {
                block.push_str(line);
                block.push('\n');
                return Some(block);
            }
            in_block = false;
            continue;
        }
        if in_block {
            block.push_str(line);
            block.push('\n');
        }
    }
    None
}

/// Write or remove the essential HVE keybind (SUPER+H) between the Lua
/// `>>> HVE KEYBINDS <<<` markers in `hve-settings.lua`. The 4 extra binds
/// (ALT+Q/N/B/S) were removed per user request (2026-09-07) — only SUPER+H
/// (toggle-tray) is vital.
/// When `enabled` is true: writes the single `hl.bind` toggle-tray bind.
/// When `enabled` is false: removes the markers and their content entirely.
/// Calls `hyprctl reload` after a successful write.
pub(crate) fn set_keybinds(enabled: bool) {
    let path = hve_settings_path();
    if !path.exists() {
        tracing::warn!("[keybinds] File not found — creating default");
        ensure_settings_file();
    }

    let content = match std::fs::read_to_string(&path) {
        Ok(c) => c,
        Err(e) => {
            tracing::error!("[keybinds] Failed to read: {}", e);
            return;
        }
    };

    let marker_start = LUA_KEYBINDS_START;
    let marker_end = LUA_KEYBINDS_END;

    // Build the replacement block when enabled — only SUPER+H is vital
    let keybinds_block: String = if enabled {
        format!(
            "{marker_start}\n\
hl.bind(\"SUPER + H\", hl.dsp.exec_cmd(\"hve-ipc toggle-tray\"))\n\
{marker_end}"
        )
    } else {
        String::new()
    };

    // Steady state: identical block already on disk → skip the rewrite
    // AND the reload (same fullscreen rationale as the window rules;
    // startup re-applies keybinds on every launch).
    let markers_present = content.contains(marker_start);
    if !enabled && !markers_present {
        return; // already clean — true no-op
    }
    if enabled
        && markers_present
        && !marker_block_needs_update(&content, marker_start, marker_end, &keybinds_block)
    {
        tracing::info!("[keybinds] already applied — skip rewrite+reload");
        return;
    }

    // Replace or remove content between markers
    let new_content = if content.contains(marker_start) {
        let mut result = String::new();
        let mut in_block = false;
        for line in content.lines() {
            if line.trim() == marker_start {
                in_block = true;
                if enabled {
                    result.push_str(&keybinds_block);
                    result.push('\n');
                }
                continue;
            }
            if line.trim() == marker_end {
                in_block = false;
                continue;
            }
            if !in_block {
                result.push_str(line);
                result.push('\n');
            }
        }
        result
    } else if enabled {
        // No markers yet → append the block
        let mut result = content;
        if !result.ends_with('\n') {
            result.push('\n');
        }
        result.push('\n');
        result.push_str(&keybinds_block);
        result.push('\n');
        result
    } else {
        // Already no markers and disabled → nothing to do
        content
    };

    match std::fs::write(&path, new_content) {
        Ok(_) => {
            tracing::info!(
                "[keybinds] {}",
                if enabled { "WRITTEN" } else { "REMOVED" }
            );
            reload_hyprland();
        }
        Err(e) => {
            tracing::error!("[keybinds] Failed to write: {}", e);
        }
    }
}

/// Path to the installed HVE binary (`~/.local/bin/hve`) when it exists and
/// is executable.
///
/// The autostart block must reference a STABLE binary. The installed copy
/// survives dev-tree moves and `cargo clean`, so it wins over `current_exe()`
/// whenever present.
fn installed_bin_path() -> Option<PathBuf> {
    let home = std::env::var("HOME").ok()?;
    let path = PathBuf::from(home).join(".local").join("bin").join("hve");
    let meta = std::fs::metadata(&path).ok()?;
    if !meta.is_file() || !is_executable(&meta) {
        return None;
    }
    Some(path)
}

#[cfg(unix)]
fn is_executable(meta: &std::fs::Metadata) -> bool {
    use std::os::unix::fs::PermissionsExt;
    meta.permissions().mode() & 0o111 != 0
}

#[cfg(not(unix))]
fn is_executable(_meta: &std::fs::Metadata) -> bool {
    true
}

/// Resolve the executable used by the autostart block, in stability order:
/// installed binary → runtime exe → bare `hve` (PATH lookup at exec time).
///
/// Fixes the persistence bug where the block baked `current_exe()` and died
/// when the dev tree moved or `cargo clean` removed `target/`.
fn resolve_autostart_exe() -> String {
    if let Some(installed) = installed_bin_path() {
        return installed.display().to_string();
    }
    std::env::current_exe()
        .unwrap_or_else(|_| PathBuf::from("hve"))
        .display()
        .to_string()
}

/// The autostart line for the bar-above sentinel, or empty when the script is
/// not where it should be.
///
/// The sentinel (`assets/scripts/hve-sentinel.py`) is a project instrument: it
/// listens to Hyprland's event socket and records the moments the shell bar
/// overlaps HVE. It is meant to live only while the HVE rewrite is in
/// progress, so it rides the autostart switch instead of owning a setting of its
/// own — one toggle, no residue, nothing to remember.
///
/// Gated on the file existing so a future cleanup cannot leave a Lua line that
/// silently fails at every session start.
fn sentinel_autostart_line() -> String {
    let script = sentinel_script_path();
    if !script.exists() {
        return String::new();
    }
    format!("\n    hl.exec_cmd(\"python3 {}\")", script.display())
}

/// Where the sentinel script is expected: next to the installed assets, so it
/// survives `cargo clean` and dev-tree moves exactly like the binary does.
fn sentinel_script_path() -> PathBuf {
    if let Some(installed) = installed_bin_path() {
        if let Some(dir) = installed.parent() {
            return dir.join("assets").join("scripts").join("hve-sentinel.py");
        }
    }
    // Dev fallback: the tracked asset next to the source tree.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("assets")
        .join("scripts")
        .join("hve-sentinel.py")
}

/// Toggle HVE autostart in `hve-settings.lua`.
///
/// When enabled, writes an `hl.on("hyprland.start", ...)` block with
/// `hl.exec_cmd("hve --tray")` between the Lua markers. When disabled,
/// removes the block entirely (markers stay in the template for next enable).
///
/// This avoids touching the user's exec.lua — everything lives in our managed file,
/// which is dofile'd from hyprland.lua. Clean uninstall: delete hve-settings.lua
/// and remove the dofile line from hyprland.lua.
pub(crate) fn set_autostart(enabled: bool) {
    let path = hve_settings_path();
    if !path.exists() {
        tracing::warn!("[autostart] hve-settings not found — creating default");
        ensure_settings_file();
    }

    let content = match std::fs::read_to_string(&path) {
        Ok(c) => c,
        Err(e) => {
            tracing::error!("[autostart] Failed to read hve-settings: {}", e);
            return;
        }
    };

    let marker_start = LUA_AUTOSTART_START;
    let marker_end = LUA_AUTOSTART_END;

    // Stable path: prefer the installed binary so the block survives dev-tree
    // moves and `cargo clean` — never bake a path that can die (see
    // resolve_autostart_exe).
    let exe = resolve_autostart_exe();

    let autostart_block: String = if enabled {
        // While the HVE project is open, the session also brings up the
        // bar-above sentinel (assets/scripts/hve-sentinel.py). It is GATED on the
        // script existing, so removing the script cannot leave a dead line, and
        // it lives inside this same block so ONE switch turns both on and off —
        // turning autostart off removes every line added here (verified by test).
        let sentinel_line = sentinel_autostart_line();
        format!(
            r#"{marker_start}
hl.on("hyprland.start", function()
    hl.exec_cmd("{exe} --tray"){sentinel_line}
end)
{marker_end}"#
        )
    } else {
        String::new()
    };

    // Same steady-state guard as keybinds/window rules: no rewrite means
    // no `hyprctl reload` means no dropped fullscreen at startup.
    let markers_present = content.contains(marker_start);
    if !enabled && !markers_present {
        return; // already clean — true no-op
    }
    if enabled
        && markers_present
        && !marker_block_needs_update(&content, marker_start, marker_end, &autostart_block)
    {
        tracing::info!("[autostart] already applied — skip rewrite+reload");
        return;
    }

    // Replace or remove content between markers
    let new_content = if content.contains(marker_start) {
        let mut result = String::new();
        let mut in_block = false;
        for line in content.lines() {
            if line.trim() == marker_start {
                in_block = true;
                if enabled {
                    result.push_str(&autostart_block);
                    result.push('\n');
                }
                continue;
            }
            if line.trim() == marker_end {
                in_block = false;
                continue;
            }
            if !in_block {
                result.push_str(line);
                result.push('\n');
            }
        }
        result
    } else if enabled {
        // No markers yet → append the block
        let mut result = content;
        if !result.ends_with('\n') {
            result.push('\n');
        }
        result.push('\n');
        result.push_str(&autostart_block);
        result.push('\n');
        result
    } else {
        // Disabled with no markers → nothing to do
        content
    };

    match std::fs::write(&path, new_content) {
        Ok(_) => {
            tracing::info!(
                "[autostart] {} in hve-settings.lua",
                if enabled { "Enabled" } else { "Disabled" }
            );
            reload_hyprland();
        }
        Err(e) => tracing::error!("[autostart] Failed to write hve-settings: {}", e),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_utils::TempEnv;

    // ── set_keybinds ─────────────────────────────────────────────────

    #[test]
    fn test_set_keybinds_writes_and_removes() {
        let _env = TempEnv::new();

        // Ensure settings file exists (always created as Lua)
        ensure_settings_file();
        assert!(hve_settings_path().exists(), "settings file should exist");

        // Enable keybinds
        set_keybinds(true);
        let content = std::fs::read_to_string(hve_settings_path()).unwrap();
        assert!(
            content.contains(">>> HVE KEYBINDS <<<"),
            "should have keybinds start marker"
        );
        assert!(
            content.contains(">>> HVE KEYBINDS END <<<"),
            "should have keybinds end marker"
        );
        assert!(content.contains("hve-ipc"), "should have hve-ipc commands");
        assert!(
            content.contains("toggle-tray"),
            "should have toggle-tray bind"
        );
        // Only SUPER+H is kept — the 4 extra ALT binds were removed (2026-09-07)
        assert!(
            !content.contains("pause-restart"),
            "should NOT have pause-restart after slim-down"
        );
        assert!(!content.contains("next-anim"), "should NOT have next-anim");
        assert!(!content.contains("next-border"), "should NOT have next-border");
        assert!(!content.contains("next-shader"), "should NOT have next-shader");

        // Disable keybinds
        set_keybinds(false);
        let content = std::fs::read_to_string(hve_settings_path()).unwrap();
        assert!(
            !content.contains(">>> HVE KEYBINDS <<<"),
            "should NOT have keybinds start marker"
        );
        assert!(
            !content.contains(">>> HVE KEYBINDS END <<<"),
            "should NOT have keybinds end marker"
        );
        assert!(
            !content.contains("hve-ipc"),
            "should NOT have hve-ipc commands"
        );
    }

    #[test]
    fn test_set_keybinds_noop_when_disabled_and_markers_absent() {
        let _env = TempEnv::new();

        // Create settings file manually WITHOUT keybinds markers
        let path = hve_settings_path();
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        let no_kb_content = "-- >>> HVE WINDOW RULES <<<\n-- HVE manages its own window state via the Composer trait\n-- >>> HVE WINDOW RULES END <<<\n";
        std::fs::write(&path, no_kb_content).unwrap();

        let before = std::fs::read_to_string(&path).unwrap();
        assert!(
            !before.contains("HVE KEYBINDS"),
            "test file should not have keybinds markers"
        );

        // Disable when no markers exist → should be no-op
        set_keybinds(false);
        let after = std::fs::read_to_string(&path).unwrap();
        assert_eq!(before, after, "disabling when markers absent should be no-op");
    }

    // ── Auto-generated header ─────────────────────────────────────────

    #[test]
    fn settings_file_created_with_generated_header() {
        let _env = TempEnv::new();

        ensure_settings_file();
        let content = std::fs::read_to_string(hve_settings_path()).unwrap();

        assert!(
            content.contains(">>> HVE AUTO-GENERATED <<<"),
            "created file must carry the auto-generated header"
        );
        assert!(
            content.contains("config.json"),
            "header must point at the source-of-truth config"
        );
        assert!(
            content.contains("Do not edit"),
            "header must warn against manual edits"
        );
    }

    #[test]
    fn settings_file_without_header_gets_header_prepended() {
        let _env = TempEnv::new();

        let path = hve_settings_path();
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        let legacy = "-- >>> HVE KEYBINDS <<<\nhl.bind(\"SUPER + H\", hl.dsp.exec_cmd(\"hve-ipc toggle-tray\"))\n-- >>> HVE KEYBINDS END <<<\n";
        std::fs::write(&path, legacy).unwrap();

        ensure_settings_file();

        let after = std::fs::read_to_string(&path).unwrap();
        assert!(
            after.contains(">>> HVE AUTO-GENERATED <<<"),
            "existing file without header must get it prepended"
        );
        assert!(
            after.contains("HVE KEYBINDS"),
            "prepending must preserve the original content"
        );
        assert!(
            after.starts_with("-- >>> HVE AUTO-GENERATED <<<"),
            "header must be the first line"
        );
    }

    // ── Startup fullscreen race: skip rewrite+reload when rules unchanged ──
    // Every `hyprctl reload` re-floats HVE and kills a pending fullscreen
    // dispatch. The startup path calls set_tiling_window_rules on EVERY
    // launch, so an unchanged file must not be rewritten nor reloaded.

    fn file_mtime(path: &std::path::Path) -> std::time::SystemTime {
        std::fs::metadata(path).unwrap().modified().unwrap()
    }

    fn assert_floating_content(content: &str) {
        // HVE manages its own window state via the Composer trait
        // (fullscreen for Gallery, floating for settings). No rules needed.
        assert!(
            content.contains("Composer trait"),
            "HVE Composer comment present in window rules"
        );
        assert!(!content.contains("tile = true"), "no tiling rule in floating mode");
    }

    fn assert_tiling_content(content: &str) {
        // HVE manages its own window state via the Composer trait
        // (fullscreen for Gallery, floating for settings). No rules needed.
        assert!(
            content.contains("Composer trait"),
            "HVE Composer comment present in window rules, got:\n{content}"
        );
    }

    #[test]
    fn tiling_rules_skip_rewrite_when_floating_already_applied() {
        let _env = TempEnv::new();
        ensure_settings_file(); // default file is floating
        set_tiling_window_rules(false); // canonicalize floating state
        let path = hve_settings_path();
        let before = std::fs::read_to_string(&path).unwrap();
        assert_floating_content(&before);
        let before_mtime = file_mtime(&path);

        set_tiling_window_rules(false);

        let after = std::fs::read_to_string(&path).unwrap();
        assert_eq!(before, after, "content must be untouched");
        assert_eq!(
            before_mtime,
            file_mtime(&path),
            "same-mode apply must NOT rewrite the file (rewrite fires hyprctl reload, which kills pending fullscreen)"
        );
    }

    #[test]
    fn tiling_rules_skip_rewrite_when_tiling_already_applied() {
        let _env = TempEnv::new();
        ensure_settings_file();
        set_tiling_window_rules(true);
        let path = hve_settings_path();
        let before = std::fs::read_to_string(&path).unwrap();
        assert_tiling_content(&before);
        let before_mtime = file_mtime(&path);

        set_tiling_window_rules(true);

        let after = std::fs::read_to_string(&path).unwrap();
        assert_eq!(before, after, "content must be untouched");
        assert_eq!(
            before_mtime,
            file_mtime(&path),
            "same-mode apply must NOT rewrite the file (rewrite fires hyprctl reload, which kills pending fullscreen)"
        );
    }

    #[test]
    fn tiling_rules_no_rewrite_since_composer_manages_state() {
        // HVE manages window state via the Composer trait, so
        // set_tiling_window_rules always writes empty rules regardless
        // of the tiling parameter. The file should never be rewritten.
        let _env = TempEnv::new();
        ensure_settings_file();
        set_tiling_window_rules(false);
        let path = hve_settings_path();
        assert_floating_content(&std::fs::read_to_string(&path).unwrap());
        let before_mtime = file_mtime(&path);

        set_tiling_window_rules(true);
        assert_tiling_content(&std::fs::read_to_string(&path).unwrap());
        assert_eq!(
            before_mtime,
            file_mtime(&path),
            "tiling mode change must NOT rewrite the file (Composer manages state)"
        );

        set_tiling_window_rules(false);
        assert_floating_content(&std::fs::read_to_string(&path).unwrap());
        assert_eq!(
            before_mtime,
            file_mtime(&path),
            "back to floating must NOT rewrite the file"
        );
    }

    #[test]
    fn marker_block_needs_update_detects_changes() {
        // Pure seam: only the block between markers decides rewrite vs skip.
        let start = "-- >>> HVE WINDOW RULES <<<";
        let end = "-- >>> HVE WINDOW RULES END <<<";
        let desired = format!("{start}\n-- tile rule\n{end}");
        let same = format!("header\n{desired}\nfooter\n");
        assert!(
            !super::marker_block_needs_update(&same, start, end, &desired),
            "identical block must not need an update"
        );
        let different = format!("header\n{start}\n-- float rule\n{end}\nfooter\n");
        assert!(
            super::marker_block_needs_update(&different, start, end, &desired),
            "different block must need an update"
        );
        assert!(
            super::marker_block_needs_update("no markers here\n", start, end, &desired),
            "missing markers must need an update"
        );
    }

    #[test]
    fn keybinds_skip_rewrite_when_already_enabled() {
        // Startup calls set_keybinds(true) on every launch — same guard as
        // the window rules: no rewrite means no extra hyprctl reload.
        let _env = TempEnv::new();
        ensure_settings_file();
        set_keybinds(true);
        let path = hve_settings_path();
        let before = std::fs::read_to_string(&path).unwrap();
        assert!(before.contains("hve-ipc"), "precondition: keybinds written");
        let before_mtime = file_mtime(&path);

        set_keybinds(true);

        assert_eq!(before, std::fs::read_to_string(&path).unwrap());
        assert_eq!(
            before_mtime,
            file_mtime(&path),
            "re-enabling identical keybinds must NOT rewrite the file"
        );
    }

    #[test]
    fn autostart_skip_rewrite_when_state_matches() {
        // Same guard for autostart: repeated applies with the same state
        // must not rewrite nor reload.
        let _env = TempEnv::new();
        ensure_settings_file();
        set_autostart(false);
        let path = hve_settings_path();
        let before = std::fs::read_to_string(&path).unwrap();
        let before_mtime = file_mtime(&path);

        set_autostart(false);

        assert_eq!(before, std::fs::read_to_string(&path).unwrap());
        assert_eq!(
            before_mtime,
            file_mtime(&path),
            "re-disabling autostart must NOT rewrite the file"
        );
    }

    // ── R2: settings path is always Lua (drop-conf-support follow-up) ──

    #[test]
    fn settings_path_always_ends_with_lua() {
        let _env = TempEnv::new();
        let path = hve_settings_path();
        assert!(
            path.to_string_lossy().ends_with("hve-settings.lua"),
            "settings path must always be the Lua file, got: {}",
            path.display()
        );
    }

    #[test]
    fn ensure_settings_file_creates_lua_and_ignores_stale_conf() {
        let _env = TempEnv::new();
        // Simulate a pre-migration system: a stale .conf file exists.
        let stale = hve_cache_dir().join("hve-settings.conf");
        std::fs::create_dir_all(stale.parent().unwrap()).unwrap();
        std::fs::write(&stale, "# >>> HVE WINDOW RULES <<<\nwindowrulev2 = float\n")
            .unwrap();

        ensure_settings_file();

        let content = std::fs::read_to_string(hve_settings_path()).unwrap();
        assert!(
            content.contains("-- >>> HVE WINDOW RULES <<<"),
            "generated file must use Lua markers"
        );
        assert!(
            !content.contains("windowrulev2"),
            "must never copy a byte from the stale .conf"
        );
        // D4: the stale .conf is orphaned, not deleted.
        assert!(stale.exists(), "stale .conf is orphaned, not deleted");
    }

    // ── R3: autostart emission is Lua (drop-conf-support follow-up) ──

    #[test]
    fn autostart_emits_lua_block_and_never_conf() {
        let _env = TempEnv::new();
        ensure_settings_file();
        set_autostart(true);
        let content = std::fs::read_to_string(hve_settings_path()).unwrap();
        assert!(
            content.contains("hl.on(\"hyprland.start\""),
            "must emit the Lua autostart block"
        );
        assert!(
            content.contains(" --tray"),
            "autostart must launch in tray mode"
        );
        assert!(
            !content.contains("exec-once ="),
            "must never emit conf syntax"
        );
    }

    #[test]
    fn autostart_starts_the_sentinel_when_its_script_is_present() {
        // The bar-above sentinel must come up with the session while the project
        // is open, and go away cleanly when autostart is turned off. It is
        // gated on the script EXISTING so a future removal cannot leave a line
        // pointing at nothing.
        let _env = TempEnv::new();
        ensure_settings_file();
        // Mirror the installed layout the real code looks at: <HOME>/.local/bin.
        let home = std::env::var("HOME").unwrap();
        let bin_dir = PathBuf::from(&home).join(".local/bin");
        let script = bin_dir.join("assets/scripts/hve-sentinel.py");
        std::fs::create_dir_all(script.parent().unwrap()).unwrap();
        std::fs::write(&script, b"#!/usr/bin/env python3\n").unwrap();
        set_autostart(true);
        let content = std::fs::read_to_string(hve_settings_path()).unwrap();
        assert!(
            content.contains("hve-sentinel.py"),
            "the sentinel must autostart with the session, got:\n{}",
            content
        );
        assert!(
            content.contains("python3"),
            "it runs through the interpreter, not as an executable"
        );
    }

    #[test]
    fn autostart_removes_the_sentinel_line_when_disabled() {
        let _env = TempEnv::new();
        ensure_settings_file();
        set_autostart(true);
        set_autostart(false);
        let content = std::fs::read_to_string(hve_settings_path()).unwrap();
        assert!(
            !content.contains("hve-sentinel"),
            "disabling autostart must remove every line it added"
        );
    }

    // ── R4: autostart must point to a STABLE binary ──
    // The block is written from the caller's current_exe(), which dies when
    // the dev tree moves or `cargo clean` runs. The installed copy under
    // ~/.local/bin/hve survives; prefer it, fall back to the runtime exe.

    #[test]
    fn autostart_prefers_installed_binary_over_runtime_exe() {
        let _env = TempEnv::new();
        let home = std::env::var("HOME").unwrap();
        let installed = PathBuf::from(&home).join(".local/bin/hve");
        std::fs::create_dir_all(installed.parent().unwrap()).unwrap();
        std::fs::write(&installed, b"#!/bin/sh\n").unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perm = std::fs::metadata(&installed).unwrap().permissions();
            perm.set_mode(0o755);
            std::fs::set_permissions(&installed, perm).unwrap();
        }

        ensure_settings_file();
        set_autostart(true);

        let content = std::fs::read_to_string(hve_settings_path()).unwrap();
        let expected = format!("{} --tray", installed.display());
        assert!(
            content.contains(&expected),
            "autostart must point to the installed binary, got: {}",
            content
        );
    }

    #[test]
    fn autostart_falls_back_to_runtime_exe_without_installed_binary() {
        let _env = TempEnv::new();
        // TempEnv HOME has no ~/.local/bin/hve → must fall back to the exe
        // that is actually running (the test binary), never to a dead path.
        ensure_settings_file();
        set_autostart(true);

        let content = std::fs::read_to_string(hve_settings_path()).unwrap();
        let exe = std::env::current_exe().unwrap();
        let expected = format!("{} --tray", exe.display());
        assert!(
            content.contains(&expected),
            "autostart must fall back to the runtime exe, got: {}",
            content
        );
    }

    #[test]
    fn installed_bin_path_ignores_non_executable_file() {
        let _env = TempEnv::new();
        let home = std::env::var("HOME").unwrap();
        let installed = PathBuf::from(&home).join(".local/bin/hve");
        std::fs::create_dir_all(installed.parent().unwrap()).unwrap();
        std::fs::write(&installed, b"not executable\n").unwrap();

        assert_eq!(
            installed_bin_path(),
            None,
            "a non-executable file must NOT qualify as the installed binary"
        );
    }

    // ── reload-config behind Composer (capability-routing Phase 3) ────

    /// Comment-stripped production body of `src/settings.rs`.
    fn settings_rs_code() -> String {
        let src = std::fs::read_to_string("src/settings.rs").expect("src/settings.rs must exist");
        src.lines()
            .filter(|l| !l.trim_start().starts_with("//"))
            .collect::<Vec<_>>()
            .join("\n")
    }

    /// Body of one `fn <sig>`: signature to matching closing brace.
    fn fn_body(src: &str, sig: &str) -> String {
        let start = src.find(sig).unwrap_or_else(|| panic!("{sig} must exist"));
        let open = src[start..].find('{').expect("the function must have a body") + start;
        let mut depth = 0usize;
        for (i, ch) in src[open..].char_indices() {
            match ch {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        return src[start..open + i + 1].to_string();
                    }
                }
                _ => {}
            }
        }
        panic!("{sig}: body must close");
    }

    #[test]
    fn reload_routes_behind_the_composer_and_keeps_the_test_gate() {
        let code = settings_rs_code();
        let body = fn_body(&code, "fn reload_hyprland()");
        assert!(
            body.contains("#[cfg(not(test))]"),
            "the deliberate test no-op gate must stay — a real reload from a test drives the \
             developer's live desktop, got: {body}"
        );
        assert!(
            body.contains("global_controller()"),
            "reload must reach the registered composer, got: {body}"
        );
        assert!(
            body.contains("reload_config"),
            "reload must use the reload-config capability verb, got: {body}"
        );
        assert!(
            body.contains("reload_config_detached"),
            "a None controller must keep the OLD spawn — never a silent no-op, got: {body}"
        );
        assert!(
            !body.contains("Command::new"),
            "settings.rs must not spawn hyprctl itself, got: {body}"
        );
    }
}
